Update Dockerfiles to use QBittorrent Enhanced Edition

diff --git a/Dockerfile.aarch64 b/Dockerfile.aarch64
--- a/Dockerfile.aarch64
+++ b/Dockerfile.aarch64
@@ -1,5 +1,3 @@
-# syntax=docker/dockerfile:1
-
 FROM ghcr.io/linuxserver/unrar:arm64v8-latest AS unrar
 
 FROM ghcr.io/linuxserver/baseimage-alpine:arm64v8-edge
@@ -21,17 +19,22 @@ XDG_DATA_HOME="/config"
 RUN \
   echo "**** install packages ****" && \
   apk add --no-cache \
+    curl \
     grep \
     icu-libs \
+    jq \
     p7zip \
     python3 \
     qt6-qtbase-sqlite && \
-  if [ -z ${QBITTORRENT_VERSION+x} ]; then \
-    QBITTORRENT_VERSION=$(curl -sL "http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz" | tar -xz -C /tmp \
-    && awk '/^P:qbittorrent-nox$/,/V:/' /tmp/APKINDEX | sed -n 2p | sed 's/^V://'); \
-  fi && \
-  apk add -U --upgrade --no-cache \
-    qbittorrent-nox==${QBITTORRENT_VERSION} && \
+  # install qbittorrent-nox enhanced
+  echo "**** install qbittorrent-nox enhanced ****" && \
+  QBEE_TAG=$(curl -sL "https://api.github.com/repos/c0re100/qBittorrent-Enhanced-Edition/releases/latest" | jq -r '.tag_name') && \
+  if [ -z "$QBEE_TAG" ]; then echo "Failed to fetch latest qbee tag" && exit 1; fi && \
+  echo "**** downloading qbee version ${QBEE_TAG} ****" && \
+  curl -o /usr/bin/qbittorrent-nox -L \
+    "https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/${QBEE_TAG}/qbittorrent-nox-static-musl-aarch64" && \
+  chmod +x /usr/bin/qbittorrent-nox && \
+  # install qbittorrent-cli
   echo "***** install qbitorrent-cli ****" && \
   mkdir /qbt && \
   if [ -z ${QBT_CLI_VERSION+x} ]; then \
